### ISSUE TITLE
Practice Task 1. presubmit_tests.py

### ISSUE THREAD

**Issue by ElDmitro** [JeanPaulShapo/hse20-opt-course#1]
Добрый день, 

При запуске базовых тестов `nosetests presubmit_tests.py` запускаются тесты и для бонусной части. Проблема локально решается добавлением нового атрибута для тестов базовой части. 

Скажите, пожалуйста, при проверке работы будут запускаться только базовые тесты, если не была выполнена бонусная часть?

Спасибо большое

**Comment by JeanPaulShapo** [comment]
Здравствуйте!
Да, бонусные тесты будет запускаться, если и только если вы сделали бонусную часть.
